global:
  resolve_timeout: 1m

route:
  receiver: "ansible-webhook"
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1m

receivers:
  - name: "ansible-webhook"
    webhook_configs:
      - url: "http://webhook_receiver:5001/alert"
        send_resolved: true
